# alacritty_0_12 — imported from alacritty/alacritty-theme
foreground = "#c5c8c6"
background = "#1d1f21"
normal = ["#1d1f21", "#cc6666", "#b5bd68", "#f0c674", "#81a2be", "#b294bb", "#8abeb7", "#c5c8c6"]
bright = ["#666666", "#d54e53", "#b9ca4a", "#e7c547", "#7aa6da", "#c397d8", "#70c0b1", "#eaeaea"]
