# ashes_light — imported from alacritty/alacritty-theme
foreground = "#565e65"
background = "#f3f4f5"
cursor = "#565e65"
cursor_foreground = "#f3f4f5"
normal = ["#1c2023", "#c7ae95", "#95c7ae", "#aec795", "#ae95c7", "#c795ae", "#95aec7", "#c7ccd1"]
bright = ["#747c84", "#c7ae95", "#95c7ae", "#aec795", "#ae95c7", "#c795ae", "#95aec7", "#f3f4f5"]
