# cyber_punk_neon — imported from alacritty/alacritty-theme
foreground = "#0abdc6"
background = "#000b1e"
cursor = "#0abdc6"
cursor_foreground = "#000b1e"
normal = ["#123e7c", "#ff0000", "#d300c4", "#f57800", "#123e7c", "#711c91", "#0abdc6", "#d7d7d5"]
bright = ["#1c61c2", "#ff0000", "#d300c4", "#f57800", "#00ff00", "#711c91", "#0abdc6", "#d7d7d5"]
