# dawnfox — imported from alacritty/alacritty-theme
foreground = "#575279"
background = "#faf4ed"
cursor = "#625c87"
cursor_foreground = "#575279"
selection = "#d0d8d8"
selection_foreground = "#575279"
normal = ["#575279", "#b4637a", "#618774", "#ea9d34", "#286983", "#907aa9", "#56949f", "#e5e9f0"]
bright = ["#5f5695", "#c26d85", "#629f81", "#eea846", "#2d81a3", "#9a80b9", "#5ca7b4", "#e6ebf3"]
