# dracula_plus — imported from alacritty/alacritty-theme
foreground = "#f8f8f2"
background = "#212121"
cursor = "#eceff4"
cursor_foreground = "#0e1415"
normal = ["#21222c", "#ff5555", "#50fa7b", "#ffcb6b", "#82aaff", "#c792ea", "#8be9fd", "#f8f9f2"]
bright = ["#545454", "#ff6e6e", "#69ff94", "#ffcb6b", "#d6acff", "#ff92df", "#a4ffff", "#f8f8f2"]
