# github_dark_high_contrast — imported from alacritty/alacritty-theme
foreground = "#f0f3f6"
background = "#0a0c10"
cursor = "#f0f3f6"
cursor_foreground = "#0a0c10"
normal = ["#7a828e", "#ff9492", "#26cd4d", "#f0b72f", "#71b7ff", "#cb9eff", "#39c5cf", "#d9dee3"]
bright = ["#9ea7b3", "#ffb1af", "#4ae168", "#f7c843", "#91cbff", "#cb9eff", "#39c5cf", "#d9dee3"]
