# github_light_high_contrast — imported from alacritty/alacritty-theme
foreground = "#010409"
background = "#ffffff"
cursor = "#0e1116"
cursor_foreground = "#ffffff"
normal = ["#0e1116", "#a0111f", "#024c1a", "#3f2200", "#0349b4", "#622cbc", "#1b7c83", "#66707b"]
bright = ["#4b535d", "#86061d", "#055d20", "#4e2c00", "#1168e3", "#622cbc", "#1b7c83", "#66707b"]
