# kanagawa_dragon — imported from alacritty/alacritty-theme
foreground = "#c5c9c5"
background = "#181616"
selection = "#2d4f67"
normal = ["#0d0c0c", "#c4746e", "#8a9a7b", "#c4b28a", "#8ba4b0", "#a292a3", "#8ea4a2", "#c8c093"]
bright = ["#a6a69c", "#e46876", "#87a987", "#e6c384", "#7fb4ca", "#938aa9", "#7aa89f", "#c5c9c5"]
