# kitty — imported from alacritty/alacritty-theme
foreground = "#dddddd"
background = "#000000"
cursor = "#cccccc"
cursor_foreground = "#111111"
normal = ["#000000", "#cc0403", "#19cb00", "#cecb00", "#0d73cc", "#cb1ed1", "#0dcdcd", "#dddddd"]
bright = ["#767676", "#f2201f", "#23fd00", "#fffd00", "#1a8fff", "#fd28ff", "#14ffff", "#ffffff"]
