# moonfly — imported from alacritty/alacritty-theme
foreground = "#bdbdbd"
background = "#080808"
cursor = "#8e8e8e"
cursor_foreground = "#080808"
selection = "#b2ceee"
selection_foreground = "#080808"
normal = ["#323437", "#ff5454", "#8cc85f", "#e3c78a", "#80a0ff", "#cf87e8", "#79dac8", "#c6c6c6"]
bright = ["#949494", "#ff5189", "#36c692", "#c6c684", "#74b2ff", "#ae81ff", "#85dc85", "#e4e4e4"]
