# nvim_dark — imported from alacritty/alacritty-theme
foreground = "#e0e2ea"
background = "#14161b"
cursor = "#e0e2ea"
cursor_foreground = "#14161b"
selection = "#4f5258"
selection_foreground = "#e0e2ea"
normal = ["#2c2e33", "#e5adb9", "#a2dfc0", "#e3ca85", "#95c5e5", "#e5b6e6", "#7edfde", "#c4c6cd"]
bright = ["#4f5258", "#ffc0b9", "#b4f6c0", "#fce094", "#a6dbff", "#ffcaff", "#8cf8f7", "#9b9ea4"]
