# one_dark — imported from alacritty/alacritty-theme
foreground = "#abb2bf"
background = "#282c34"
normal = ["#1e2127", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#abb2bf"]
bright = ["#5c6370", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#ffffff"]
