# terafox — imported from alacritty/alacritty-theme
foreground = "#e6eaea"
background = "#152528"
cursor = "#cbd9d8"
cursor_foreground = "#e6eaea"
selection = "#293e40"
selection_foreground = "#e6eaea"
normal = ["#2f3239", "#e85c51", "#7aa4a1", "#fda47f", "#5a93aa", "#ad5c7c", "#a1cdd8", "#ebebeb"]
bright = ["#4e5157", "#eb746b", "#8eb2af", "#fdb292", "#73a3b7", "#b97490", "#afd4de", "#eeeeee"]
