# tomorrow_night — imported from alacritty/alacritty-theme
foreground = "#c5c8c6"
background = "#1d1f21"
cursor = "#ffffff"
cursor_foreground = "#1d1f21"
normal = ["#1d1f21", "#cc6666", "#b5bd68", "#e6c547", "#81a2be", "#b294bb", "#70c0ba", "#373b41"]
bright = ["#666666", "#ff3334", "#9ec400", "#f0c674", "#81a2be", "#b77ee0", "#54ced6", "#282a2e"]
